services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
